### ISSUE TITLE
argument of type 'NoneType' is not iterable (when updating)

### ISSUE THREAD

**Issue by luocy16** [man-group/arctic#923]
#### Arctic Store

ChunkStore

#### Platform and version

Linux

#### Description of problem and/or code sample that reproduces the issue

I don't know where the bug is.

File "/home/shared_user/anaconda3/envs/luocy2/lib/python3.8/site-packages/arctic/serialization/numpy_arrays.py", line 220, in deserialize
    index = INDEX in metaTraceback (most recent call last):
  File "create_dataset_new.py", line 100, in add_one_stock_daily_data_wrapper
    error_index_list = add_one_stock_daily_data(filepath, type, exchange_place, arc, date)
  File "create_dataset_new.py", line 86, in add_one_stock_daily_data
    lib.update(symbol, df, chunk_size="D")
  File "/home/shared_user/anaconda3/envs/luocy2/lib/python3.8/site-packages/arctic/chunkstore/chunkstore.py", line 567, in update
    self.__update(sym, item, metadata=metadata, combine_method=lambda old, new: new, chunk_range=chunk_range, audit=audit)
  File "/home/shared_user/anaconda3/envs/luocy2/lib/python3.8/site-packages/arctic/chunkstore/chunkstore.py", line 433, in __update
    df = self.read(symbol, chunk_range=chunker.to_range(start, end), filter_data=False)
  File "/home/shared_user/anaconda3/envs/luocy2/lib/python3.8/site-packages/arctic/chunkstore/chunkstore.py", line 287, in read
    return deser(chunks[symbol[0]], **kwargs) if skip_filter else chunker.filter(deser(chunks[symbol[0]], **kwargs), chunk_range)
  File "/home/shared_user/anaconda3/envs/luocy2/lib/python3.8/site-packages/arctic/serialization/numpy_arrays.py", line 220, in deserialize
    index = INDEX in meta
TypeError: argument of type 'NoneType' is not iterable

**Comment by bmoscon** [comment]
you'll have to post a reproducible example so we can take a look

**Comment by jasonlocal** [comment]
Hi @luocy16 , we can definitely help if you give us an example to replicate the problem. If this is not an issue anymore, we would like to close the ticket

**Comment by jasonlocal** [comment]
ticket clean up - can be reopened  if the user follow up

**Comment by TwoBeng** [comment]
I also encountered the same bug. When the original  collection has this row of data, but the metadata collection does not have this row of data, this bug will occur when updating
